config/routes.rb
WorldFood::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :countries
  resources :country_users

  root :to => 'countries#index'
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name

  has_many :country_users
  has_many :checkins, :through => :country_users

  def yelp_results(city, country)
    client = Yelp::Client.new

    request = Yelp::V2::Search::Request::Location.new(
      city: city,
      term: "#{country} restaurant",
      consumer_key: Figleaf::Settings.yelp.consumer_key,
      consumer_secret: Figleaf::Settings.yelp.consumer_secret,
      token: Figleaf::Settings.yelp.token,
      token_secret: Figleaf::Settings.yelp.token_secret
    )

    HashWithIndifferentAccess.new(client.search(request))
  end

  def checkin_for(user)
    country_users.where(user_id: user.id).first_or_initialize
  end
end

app/models/country_user.rb
class CountryUser < ActiveRecord::Base
  attr_accessible :checked, :country_id, :user_id

  belongs_to :country
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email
  attr_accessible :first_name
  attr_accessible :image
  attr_accessible :last_name
  attr_accessible :location
  attr_accessible :name
  attr_accessible :nickname
  attr_accessible :oauth_expires_at
  attr_accessible :oauth_token
  attr_accessible :provider
  attr_accessible :uid

  has_many :country_users
  has_many :checkins, :through => :country_users

  def self.from_omniauth(auth)
      where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
        user.email = auth.info.email
        user.first_name = auth.info.first_name
        user.image = auth.info.image
        user.last_name = auth.info.last_name
        user.location = auth.info.location
        user.name = auth.info.name
        user.nickname = auth.info.nickname
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.oauth_token = auth.credentials.token
        user.provider = auth.provider
        user.uid = auth.uid
        user.save!
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @countries }
    end
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    @country = Country.find(params[:id])
    @location = current_user ? current_user.location : 'Paris'
    @results = @country.yelp_results(@location, @country.name)[:businesses]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/new
  # GET /countries/new.json
  def new
    @country = Country.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/1/edit
  def edit
    @country = Country.find(params[:id])
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(params[:country])

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render json: @country, status: :created, location: @country }
      else
        format.html { render action: "new" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /countries/1
  # PUT /countries/1.json
  def update
    @country = Country.find(params[:id])

    respond_to do |format|
      if @country.update_attributes(params[:country])
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country = Country.find(params[:id])
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/country_users_controller.rb
class CountryUsersController < ApplicationController
  def create
    @params = params[:country_user]
    @checkin = CountryUser.where(country_id: @params[:country_id], user_id: current_user.id).first_or_initialize
    @checkin.checked = @params[:checked]
    @checkin.save

    redirect_to root_path
  end

  def update
    @params = params[:country_user]
    @checkin = CountryUser.where(country_id: @params[:country_id], user_id: current_user.id).first_or_initialize
    @checkin.checked = @params[:checked]
    @checkin.save

    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_if_path_is(path)
    'active' if request.path == path
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/application/_navigation.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <%= link_to "WorldFood", root_path, class: "brand" %>
    <ul class="nav">
      <li class="<%= active_if_path_is(countries_path) %>"><%= link_to "Countries", countries_path %></li>
    </ul>

    <ul class="nav pull-right">
      <% if current_user %>
        <li><%= link_to current_user.name, root_path %></li>
        <li><%= link_to "Sign out", signout_path %></li>
      <% else %>
        <li><%= link_to "Sign in with Facebook", "/auth/facebook" %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<ul>
  <% @countries.each do |country| %>
    <li>
      <% if current_user %>
        <%= form_for country.checkin_for(current_user) do |f| %>
          <fieldset>
            <label class="checkbox">
              <%= f.text_field :country_id, type: "hidden" %>
              <%= f.check_box :checked %>
              <%= link_to country.name, country %>
            </label>
          </fieldset>
        <% end %>
      <% else %>
        <%= link_to country.name, country %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<h1><%= @country.name %></h1>

<p>
  Best restaurants in <%= @location %>
  <% unless current_user %>
    (<%= link_to "sign in with Facebook", "/auth/facebook" %> to change your location.)
  <% end %>
</p>


<ul>
  <% @results.each do |result| %>
    <li>
      <%= image_tag(result[:rating_img_url]) %>
      <%= link_to result[:name], result[:url] %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorldFood</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "navigation" %>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>